// <auto-generated />
using System;
using Api.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210608090353_User_Uf_County_Cep")]
    partial class User_Uf_County_Cep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cep")
                        .IsUnique();

                    b.HasIndex("CountyId");

                    b.ToTable("Ceps");
                });

            modelBuilder.Entity("Api.Domain.Entities.CountyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CodeIBGE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("UfId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CodeIBGE")
                        .IsUnique();

                    b.HasIndex("UfId");

                    b.ToTable("Counties");
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Initials")
                        .IsUnique();

                    b.ToTable("Ufs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7462),
                            Initials = "AC",
                            Name = "Acre"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7615),
                            Initials = "AL",
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7632),
                            Initials = "AM",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7645),
                            Initials = "AP",
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7654),
                            Initials = "BA",
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7663),
                            Initials = "CE",
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7671),
                            Initials = "DF",
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7680),
                            Initials = "ES",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7689),
                            Initials = "GO",
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7697),
                            Initials = "MA",
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7705),
                            Initials = "MG",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7714),
                            Initials = "MS",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7723),
                            Initials = "MT",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7731),
                            Initials = "PA",
                            Name = "Pará"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7739),
                            Initials = "PB",
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7748),
                            Initials = "PE",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7756),
                            Initials = "PI",
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7765),
                            Initials = "PR",
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7774),
                            Initials = "RJ",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7782),
                            Initials = "RN",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7792),
                            Initials = "RO",
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7801),
                            Initials = "RR",
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7810),
                            Initials = "RS",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7818),
                            Initials = "SC",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7827),
                            Initials = "SE",
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7837),
                            Initials = "SP",
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 405, DateTimeKind.Utc).AddTicks(7846),
                            Initials = "TO",
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b99f215d-721e-4b04-b059-119a1864fc8f"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 398, DateTimeKind.Utc).AddTicks(8608),
                            Email = "user@example.com",
                            Name = "User Padrão",
                            UpdateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(376)
                        },
                        new
                        {
                            Id = new Guid("1d91565f-c033-41dc-95e9-ef8b2291df4e"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(1114),
                            Email = "eskokado@email.com",
                            Name = "Edson Shideki Kokado",
                            UpdateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(1130)
                        },
                        new
                        {
                            Id = new Guid("48b270a8-4cd7-4af1-aa45-449be3555512"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(1166),
                            Email = "mariasilva@email.com",
                            Name = "Maria da Silva",
                            UpdateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(1168)
                        },
                        new
                        {
                            Id = new Guid("4dcb8b0b-bbf5-4e38-88ad-38c483033ddd"),
                            CreateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(1172),
                            Email = "josesouza@email.com",
                            Name = "José Souza",
                            UpdateAt = new DateTime(2021, 6, 8, 9, 3, 52, 399, DateTimeKind.Utc).AddTicks(1174)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.CountyEntity", "County")
                        .WithMany("Ceps")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("Api.Domain.Entities.CountyEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.UfEntity", "Uf")
                        .WithMany("Counties")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("Api.Domain.Entities.CountyEntity", b =>
                {
                    b.Navigation("Ceps");
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Navigation("Counties");
                });
#pragma warning restore 612, 618
        }
    }
}
